Team-Pickify/Pickfy-FE

- src/apis/axiosInstance.js
- src/pages/admin/magazine/MangeMagazine.jsx
close:
- #
> 나중에 유지보수도 편하게하고, api 연결할때 편리하게 하라고 axios 객체 생성해놨습니다
> X
> 문제 있으면 알려주세여
> ✨ Feat: axios 객체 생성

- src/pages/main/map.jsx
close:
- #번호
> 상태에 따른 바텀시트 화면 구현 중에 1차 머지.
> ✨ Feat: 바텀시트 수정

- package-lock.json
- package.json
- src/apis/axiosInstance.js
- src/components/InfoSmall.jsx
- src/pages/login/login.jsx
- src/pages/placeList/index.jsx
- vite.config.js
- yarn.lock
close:
- #번호
> 인스턴스 구축 수정
- react-cookie 설치
- 의존성 문제 해결(예외처리)
로그인 토큰을 쿠키로 받아오기위해 쿠키허용 및 요청 인터셉터에서 쿠키의 토큰을 가져와 헤더에 추가
> axios 인스턴스 수정

- src/pages/main/map.jsx
close:
- #번호
> api 1차연동 및 바텀시트 수정 
> 카테고리 눌렀을때 마킹 잘 되는지 확인해주시고 마커 눌렀을 때 마킹 잘 되는지 확인해주세요. 바텀시트 끝까지 올라간 화면은 아직 구현 중입니다.
> ✨ feat/api연동 1차 및 바텀시트 2차수정

- src/hooks/Marking.jsx
- src/hooks/createMap.jsx
- src/hooks/findLocation.jsx
- src/hooks/getCategorylist.jsx
- src/hooks/getMagazinelist.jsx
- src/hooks/getPlaceData.jsx
close:
- #번호
> api관련 함수들 컴포넌트화
> ✨ feat/ api관련 함수들 컴포넌트화

- src/apis/axiosInstance.js
- src/components/InfoSmall.jsx
close:
- #번호
> axiosInstance.js 파일 수정
토큰을 받아오는 걸로 해야했는데 수정한걸 안올렸었네요 ㅜㅜ
> axiosInstance수정

- src/apis/axiosInstance.js
- src/pages/login/login.jsx
close:
- #번호
네트워크에 포함되어있던 토큰이 콘솔에 찍히지 않던 (undefined로 뜸)문제 해결
-> `Access-Control-Expose-Headers: Authorization` : 서버쪽 코드를 수정했습니다
> 🚨hotfix:헤더에서 액세스 토큰 추출

- src/apis/axiosInstance.js
- src/components/Info.jsx
- src/components/InfoSmall.jsx
- src/pages/placeList/index.jsx
close:
- #번호
- (임시)로그인 시 액세스토큰으로 사용하도록 변경
- 마이플레이스 리스트 페이지에서 이미지 띄우기(변수수정)
- 모바일 뷰에서 공유버튼 수정
> 마이플레이스 리스트 수정

- src/apis/axiosInstance.js
- src/pages/placeList/index.jsx
close:
- #번호
액세스토큰 받아오도록 수정, (임시..)
미안합니다...오타에요....
> 🚨hotfix:인스턴스 수정

- vite.config.js
close:
- #번호
배포에러가 나서 절대경로 설정했어요
> fix: 절대경로 설정

- yarn.lock
close:
- #
> 처음 페이지 접속 시 로그인 페이지로 이동하게 하 는 코드 주석 해제
> X
> X
> 🐛 Fix: 처음 페이지 접속 시 로그인 페이지로 이동하게 하는 코드 주석 해제

- src/pages/main/map.jsx
close:
- #번호
> 바텀시트 제작 완료
> 아직 더미데이터에 이미지가 추가되지 않아서 이미지까지 잘나오는지는 확인을 못한 상태입니다!
> ✨ 바텀시트 구현 (2차)

- src/hooks/Marking.jsx
- src/hooks/getPlaceData.jsx
> 플레이스 조회 컴포넌트, 지도 마킹 컴포넌트 약간 수정
> ✨Feat/map component

- src/components/Linkbox.jsx
- src/pages/setting/index.jsx
close:
- #
> 설정 페이지 API 연동 완료
> X
> 드디어 끝,,, 아마도,,, 리팩토링 시작해야지
> ✨ Feat: 설정 페이지 API 연동 완료

- dev-dist/sw.js
- src/components/modal/shareUrl.jsx
close:
- #번호
> 공유하기 기능추가 
카카오톡 공유가 아닌 모바일 상에서 원하는 곳으로 공유할 수 있도록 함
> ✨feat: 공유하기 기능 추가

- src/components/InputBox.jsx
- src/components/LoginBtn.jsx
- src/components/toast/WhiteToast.jsx
- src/navigator/routes.jsx
- src/pages/login/OAuth.jsx
- src/pages/login/login.jsx
- src/pages/login/resetPassword.jsx
- src/pages/login/signup.jsx
- vite.config.js
- yarn.lock
> Feat: 소셜로그인 api 연동

- src/pages/login/login.jsx
close:
- #번호
사용자와 관리자 로그인에 따른 라우팅 설정
> ✨feat: 로그인시 사용자 역할에 따른 라우팅 설정

- src/hooks/mapApi/getMyPlcaeData.jsx
- src/hooks/mapApi/selectarray.jsx
- src/pages/main/map.jsx
> 유저가 저장한 플레이스 조회 기능들을 구현하였습니다.
> ✨Feat: 유저가 저장한 플레이스 조회 기능 구현

- dev-dist/sw.js
- src/pages/login/admin-login.jsx
- src/pages/login/login.jsx
close:
- #번호
> 로그인 role 정보를 쿠키에 저장
> ✨Feat: 로그인 role 추가

- src/pages/login/admin-login.jsx
close:
- #번호
> 관리자로그인 후 이동 경로 수정
> ✨Feat: 관리자 로그인 후 이동 경로 수정

- dev-dist/sw.js
- src/components/Info.jsx
- src/components/categoryBtn.jsx
close:
- #번호
저장 토글 api연결 -> 확인필요함
카테고리 종류 연결
> ✨마이 플레이스리스트 api연결 수정

- src/hooks/mapApi/Marking.jsx
- src/hooks/mapApi/getPlaceData.jsx
- src/hooks/mapApi/selectarray.jsx
- src/pages/main/map.jsx
close:
- #번호
> 카테고리 버튼 앞에 패딩 추가
> ✨Feat : 카테고리 버튼 패딩추가

- dev-dist/sw.js
- package-lock.json
- src/components/Dropdown_Order.jsx
- src/hooks/mapApi/Marking.jsx
- src/pages/main/map.jsx
- vite.config.js
- yarn.lock
close:
- #번호
> 바텀시트 플레이스 정렬 기능 구현 및 일부코드 수정
> ✨ Feat: 바텀시트 플레이스 정렬 기능 구현

- dev-dist/sw.js
- src/components/InputBox.jsx
- src/components/LogoBox.jsx
close:
- #번호
> 로고 위로 배치, 이용약관 디자인 수정
> 💄로고 위로 배치, 이용약관 디자인 수정

- dev-dist/sw.js
- src/pages/login/admin-login.jsx
- src/pages/login/login.jsx
- src/pages/login/resetPassword.jsx
- src/pages/login/signup.jsx
> 🍱 로고 이미지 png로 변경 

- dev-dist/sw.js
- src/components/categoryBtn.jsx
- src/pages/placeList/index.jsx
> ✨마이플레이스리스트 수정

- src/components/header/HeaderBtn.jsx
close:
- #번호
헤더에서 공유버튼 눌렀을 때 공유모달 뜨도록 수정
> 🐛fix: 헤더 공유버튼 클릭시 공유모달 뜨도록 수정

- dev-dist/sw.js
- src/pages/admin/place/AddPlace.jsx
- src/pages/login/admin-login.jsx
- src/pages/login/login.jsx
- vite.config.js
close:
- #
> 🐛 Fix: API URL 올바르게 수정
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> 🐛 Fix: API URL 올바르게 수정

- src/pages/main/map.jsx
> ✨feat:  지도 컴포넌트 수정

- dev-dist/sw.js
- src/pages/admin/magazine/MangeMagazine.jsx
- src/pages/admin/place/ManagePlace.jsx
close:
- #번호
> 🐛 Fix: 배경 높이 늘림
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> 🐛 Fix: 배경 높이 늘림

- dev-dist/sw.js
- src/components/categoryBtn.jsx
- src/pages/placeList/index.jsx
> 🐛카테고리 컴포넌트 수정

- dev-dist/sw.js
- src/components/categoryBtn.jsx
- src/pages/placeList/index.jsx
> ✨제발 수정되어라 카테고리버튼

- package.json
- src/components/Info.jsx
close:
- #번호
"/places/toggle" 연동 로직 확인중
> 🐛플레이스 저장로직 수정

- src/apis/placelist/heartToggle.jsx
- src/components/Info.jsx
- src/components/InfoSmall.jsx
close:
- #번호
왜 cors랑 200이 한번에 뜰까
> 🐛fix: 저장로직 수정중

- dev-dist/sw.js
- src/components/Info.jsx
- src/components/categoryBtn.jsx
- src/pages/placeList/index.jsx
> 🐛카테고리 버튼 수정

- src/hooks/mapApi/Marking.jsx
- src/hooks/mapApi/getPlaceData.jsx
- src/pages/main/map.jsx
close:
- #번호
> 코드 리팩토링 및 일부 수정
> ✨ 코드 일부 수정

- src/components/Info.jsx
- src/components/InfoSmall.jsx
- src/components/categoryBtn.jsx
- src/pages/placeList/index.jsx
close:
- #번호
에러 수정 및 저장 플레이스 하트보여주기
> length 에러 수정

- dev-dist/sw.js
- src/components/categoryBtn.jsx
- vite.config.js
close:
- #번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> fix: 배포 문제해결 되어라..

- src/components/categoryBtn.jsx
close:
- #번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> fix: 카테고리버튼 뒤로 돌리기

- src/components/Info.jsx
close:
- #번호
하트 토글 시 값이 바로 갱신 되도록 수정
> 🐛fix:useEffect로 갱신

- dev-dist/sw.js
- src/components/InputBox.jsx
> 💄 이용약관 줄바꿈 수정

- dev-dist/sw.js
- src/components/categoryBtn.jsx
- src/pages/placeList/index.jsx
> ✨feat: 카테고리, 드롭다운 정렬

- dev-dist/sw.js
- src/pages/admin/place/ManagePlace.jsx
close:
- #번호
> ✨ Feat: 관리자 페이지 페이지네이션 추가
> 다들 고생했다!!
> ✨ Feat: 관리자 페이지 페이지네이션 추가

- src/components/Info.jsx
- src/components/modal/shareUrl.jsx
> 공유하기 url수정
